package:
  name: chainctl
  version: 1.0.0
  epoch: 0
  description: "Chainguard chainctl CLI"
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - curl    

pipeline:
  - name: Download chainctl (always latest, cache-busted)
    runs: |
      set -euo pipefail
      OS="$(uname -s | tr '[:upper:]' '[:lower:]')"          # linux or darwin
      ARCH="$(uname -m | sed 's/aarch64/arm64/')"            # normalize
      TS="$(date +%s)"                                       # unique per build
      URL="https://dl.enforce.dev/chainctl/latest/chainctl_${OS}_${ARCH}?ts=${TS}"

      rm -f chainctl
      curl -fL --show-error --retry 5 --retry-connrefused \
        -H 'Cache-Control: no-cache, no-store, max-age=0' \
        -H 'Pragma: no-cache' \
        -o chainctl "${URL}"
      chmod +x chainctl

      # Optional: print the version we actually got
      ./chainctl version || true

  - name: Install chainctl
    runs: |
      install -Dm755 ./chainctl "${{targets.destdir}}"/usr/local/bin/chainctl
