package:
  name: container-adoption-report
  version: 1.0.0
  epoch: 0
  description: "Chainguard container adoption report script"
  target-architecture:
    - x86_64
    - aarch64  
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox   

pipeline:
  - name: Install script
    runs: |
      install -Dm755 "${{package.srcdir}}"/container-adoption-report "${{targets.destdir}}"/usr/local/bin/container-adoption-report
